spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helloboard?useUnicode=true&charaterEncoding=utf-8
    username: fastcamp
    password: fastcamp
    initialization-mode: always
  h2:
    console:
      enabled: true